name: build & test
on: 
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - development
env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_NOLOGO: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  build-windows:
    name: build release and debug for windows
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: 3.1.300
    - name: build debug
      run: |
        dotnet build src/Exomia.Framework --configuration Debug --force --nologo -p:Platform=AnyCPU
        dotnet build src/Exomia.Framework --configuration Debug --force --nologo -p:Platform=x86
        dotnet build src/Exomia.Framework --configuration Debug --force --nologo -p:Platform=x64
    - name: build release
      run: |
        dotnet build src/Exomia.Framework --configuration Release --force --nologo -p:Platform=AnyCPU
        dotnet build src/Exomia.Framework --configuration Release --force --nologo -p:Platform=x86
        dotnet build src/Exomia.Framework --configuration Release --force --nologo -p:Platform=x64
  test-windows:   
    name: test release and debug for windows
    needs: [build-windows]
    runs-on: windows-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: 3.1.300
    - name: test debug
      run: |
        dotnet test tests/L0/Exomia.Framework.Tests --configuration Debug --nologo -p:Platform=AnyCPU
        dotnet test tests/L0/Exomia.Framework.Tests --configuration Debug --nologo -p:Platform=x86
        dotnet test tests/L0/Exomia.Framework.Tests --configuration Debug --nologo -p:Platform=x64
    - name: test release
      run: |
        dotnet test tests/L0/Exomia.Framework.Tests --configuration Release --nologo -p:Platform=AnyCPU
        dotnet test tests/L0/Exomia.Framework.Tests --configuration Release --nologo -p:Platform=x86
        dotnet test tests/L0/Exomia.Framework.Tests --configuration Release --nologo -p:Platform=x64