name: check build success and run tests
on: 
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - development
jobs:
  build:
    name: build release and debug
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v2
      uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: 3.1.300
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
     - name: build debug
     - run: dotnet build src/Exomia.Framework --configuration Debug --force --nologo
     - name: build release
     - run: dotnet build src/Exomia.Framework --configuration Release --force --nologo
  test:    
    name: test release and debug
    needs: [build]
    runs-on: windows-latest
    steps:    
    - uses: actions/checkout@v2
      uses: actions/setup-dotnet@v1   
      with:
        dotnet-version: 3.1.300
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: test debug
    - run: dotnet test tests/L0/Exomia.Framework.Tests --configuration Debug --nologo
    - name: test release
    - run: dotnet test tests/L0/Exomia.Framework.Tests --configuration Release --nologo
